"""Dormant subgraph — patient has gone silent after backoff exhaustion.

No outbound messages. If patient reaches out, transition to RE_ENGAGING
for warm re-engagement.
"""

from __future__ import annotations

from typing import Any

from ai_health_coach.core.simulation import get_current_date
from ai_health_coach.core.state.schemas import (
    PHASE_RE_ENGAGING,
    DormantState,
    PatientState,
)


def enter_dormant(parent_state: PatientState) -> dict[str, Any]:
    """Mark the patient as dormant. No message sent."""
    dormant_state = DormantState(
        dormant_since=get_current_date(),
        reactivation_message=None,
    )
    return {
        "response": None,
        "dormant_state": dormant_state,
        "parent_updates": {},
    }


def handle_dormant_message(
    parent_state: PatientState,
    patient_message: str,
) -> dict[str, Any]:
    """Patient reached out while dormant — transition to RE_ENGAGING.

    The actual response is generated by the re_engaging subgraph.
    """
    dormant_state = DormantState(
        dormant_since=parent_state.get("last_contact_date", get_current_date()),
        reactivation_message=patient_message,
    )
    return {
        "response": None,  # Router will dispatch to re_engaging
        "dormant_state": dormant_state,
        "parent_updates": {
            "phase": PHASE_RE_ENGAGING,
        },
    }
